language: python

services:
  - docker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

script:
  - docker build -t bwoods/ltr .
  - docker run bwoods/ltr jupyter nbconvert --to notebook --execute work/*.ipynb
